### ISSUE TITLE
Swift Package支持

### ISSUE THREAD

**Issue by GitHubyangjunyi** [MengLiMing/EasyKits#1]
大佬 有没有分离各个子项作为单独的Swift Package进行分发或者单个Swfit Package提供不同Product的想法

**Comment by MengLiMing** [comment]
> 大佬有没有不同的组件提供作为单独的Swift Package 进行分发或者不同Swfit Package 的产品的关联

好的 安排

**Comment by MengLiMing** [comment]
> 大佬 有没有分离各个子项作为单独的Swift Package进行分发或者单个Swfit Package提供不同Product的想法

已经支持SPM，因为IGListKit的SPM支持[有问题](https://github.com/Instagram/IGListKit/issues/1557), 所以采用了未验证的版本。如果不使用EasyIGListKit可以不关心这个。
